Support multiple indexer-service endpoints
semiotic-ai/autoagora pull request #49
Opened 2023-01-13 18:16 UTC by madumas

To fix issue #48, this allows specify more than one endpoint in `--indexer-service-metrics-endpoint`. `subgraph_query_count` sums the metrics from the different endpoints for a given subgraph.

Also removes some extra code and add tests.

2023-01-13 22:23 UTC, aasseman requested changes
Very nice! Thanks!
Could you also run black / isort / pyright?

2023-01-13 22:23 UTC, aasseman commented on pyproject.toml
> +vcrpy = "^4.2.1"
`vcrpy` should be moved into the  dev dependencies below

2023-01-23 22:40 UTC, aasseman requested changes
There is an issue with the history, probably due to the merging of master into this branch. That caused some things to get un-removed (such as `vcrpy` in the main dependencies, or line 114 in `config.py`).
I would suggest an interactive rebase onto master to fix the history.

In general, catching up to the target branch through rebasing is safer and cleaner than merging.

2023-01-24 15:30 UTC, madumas commented
it should be fine now

2023-01-24 22:35 UTC, aasseman approved these changes
Thanks for bearing with me through the review process! Your contribution is much appreciated.
Also I really like the tests using `vcrpy` :slightly_smiling_face: .

2023-01-24 22:36 UTC, merged